// Glossary — each term gets an anchor (#term-slug) and is included in DefinedTermSet schema.
export type Term = { term: string; def: string; related?: string };

export const glossary: Term[] = [
  { term: "Acrylic emulsion", def: "A milky-white dispersion of acrylic polymer particles in water, made by emulsion polymerisation. Used as the binder in water-based paints, adhesives, textile binders and construction chemicals.", related: "/products/paint-coatings-emulsions" },
  { term: "Alkali resistance", def: "The ability of a paint film or polymer to withstand the high pH of fresh cement, plaster and concrete without saponifying, softening or discolouring." },
  { term: "APEO", def: "Alkylphenol ethoxylates — surfactants historically used in emulsion polymerisation. Restricted by many textile and consumer-goods compliance programmes; buyers increasingly ask for APEO-free binders.", related: "/learning-center/apeo-free-formaldehyde-free-textile-binders" },
  { term: "Binder", def: "The film-forming component of a paint, coating or print paste that holds pigment and filler together and bonds them to the substrate." },
  { term: "Block board", def: "A wood panel with a core of solid softwood strips sandwiched between veneers. Commonly bonded and laminated with synthetic resin adhesives." },
  { term: "Bond strength", def: "The force required to separate two bonded surfaces, usually measured as tensile shear strength in N/mm² in adhesive tests such as EN 205." },
  { term: "Clamping time", def: "The minimum time assembled parts must be held under pressure for the adhesive to develop enough strength to handle the joint." },
  { term: "Closed assembly time", def: "Time between bringing the glued surfaces together and applying full pressure. Too long and the glue skins, weakening the bond." },
  { term: "Coalescing agent", def: "A slow-evaporating solvent added to emulsion paints to temporarily soften polymer particles so they fuse into a continuous film below their natural MFFT." },
  { term: "Coverage (spread rate)", def: "The quantity of adhesive or paint applied per unit area, typically g/m² for adhesives or m²/litre for paints.", related: "/tools/coverage-calculator" },
  { term: "CPVC", def: "Critical Pigment Volume Concentration — the PVC at which there is just enough binder to wet all pigment and extender particles. Above CPVC, films become porous and lose scrub and stain resistance." },
  { term: "D1 / D2 / D3 / D4", def: "Durability classes for thermoplastic wood adhesives defined in EN 204. D1 is for dry interiors; D2 for interiors with occasional short-term water or humidity; D3 for interiors with frequent short-term water exposure and exteriors not exposed to weather; D4 for frequent long-term water exposure and weather-exposed exteriors with surface protection.", related: "/learning-center/d1-d2-d3-d4-wood-adhesive-classes-en-204-explained" },
  { term: "Defoamer", def: "An additive that destroys or prevents foam during paint or adhesive manufacture and application.", related: "/products/additives" },
  { term: "Delamination", def: "Separation of bonded layers — for example laminate lifting from plywood — typically caused by moisture, wrong adhesive class, poor spread or insufficient pressure." },
  { term: "Dispersant", def: "An additive that wets and stabilises pigment particles in a liquid, improving grind efficiency and colour strength and preventing flocculation." },
  { term: "Edge banding", def: "Thin strips of PVC, ABS, veneer or laminate applied to exposed board edges in furniture. Hot-melt or PVAc adhesives are used depending on the process." },
  { term: "Emulsion polymerisation", def: "A process in which monomers are polymerised as tiny droplets/particles dispersed in water using surfactants and an initiator, producing a latex or emulsion.", related: "/learning-center/how-emulsion-polymerisation-works" },
  { term: "EN 204", def: "European standard that classifies non-structural thermoplastic wood adhesives into durability classes D1–D4." },
  { term: "EN 205", def: "European test method for determining the tensile shear strength of lap joints bonded with wood adhesives, used to verify EN 204 classes." },
  { term: "Extender", def: "Low-cost mineral fillers such as calcium carbonate, talc and china clay that add bulk and modify properties of paints and putty." },
  { term: "Formaldehyde-free", def: "Products formulated without formaldehyde-releasing components — important for indoor air quality and textile compliance." },
  { term: "Glass transition temperature (Tg)", def: "The temperature at which a polymer changes from hard and glassy to soft and rubbery. Tg strongly influences film hardness, flexibility and dirt pickup.", related: "/learning-center/mfft-and-tg-emulsion-polymers-explained" },
  { term: "Hand (textile)", def: "The feel of a fabric. Soft-hand binders produce prints that don't stiffen the fabric." },
  { term: "Hot press", def: "A heated hydraulic press used to bond veneers or laminates to boards quickly. Adhesives must be suited to the press temperature and cycle time.", related: "/learning-center/laminate-pasting-adhesive-hot-press-cold-press" },
  { term: "Cold press", def: "A room-temperature press used for laminate or veneer bonding with longer pressing times than a hot press." },
  { term: "Laminate (decorative)", def: "High-pressure decorative sheets (often called sunmica) bonded to plywood or MDF with synthetic resin adhesives." },
  { term: "Latex", def: "A stable dispersion of polymer particles in water. Natural rubber latex comes from Hevea trees; synthetic latexes (emulsions) are made by emulsion polymerisation." },
  { term: "MDF", def: "Medium Density Fibreboard — an engineered wood panel made from wood fibres and resin, widely used in modular furniture." },
  { term: "MFFT", def: "Minimum Film Forming Temperature — the lowest temperature at which an emulsion coalesces into a continuous, crack-free film.", related: "/learning-center/mfft-and-tg-emulsion-polymers-explained" },
  { term: "Open time", def: "The time after spreading adhesive during which parts can still be assembled and form a good bond." },
  { term: "Particle size", def: "The average diameter of polymer particles in an emulsion. Finer particle size generally improves penetration, binding power and gloss." },
  { term: "Pigment printing", def: "A textile printing method where insoluble pigments are fixed to the fabric surface using a polymer binder and heat curing.", related: "/learning-center/textile-pigment-printing-binder-guide" },
  { term: "Polymer-modified mortar", def: "Cement mortar with added polymer emulsion or powder that improves adhesion, flexibility and water resistance.", related: "/learning-center/polymer-modified-mortar-sbr-vs-acrylic" },
  { term: "Pure acrylic", def: "A polymer made only from acrylic and methacrylic monomers — known for excellent UV resistance and gloss retention in exterior paints." },
  { term: "PVAc", def: "Polyvinyl acetate — the polymer behind most white wood glues (synthetic resin adhesives)." },
  { term: "PVC (paints)", def: "Pigment Volume Concentration — the volume percentage of pigment and extender in the dry paint film. Not to be confused with polyvinyl chloride." },
  { term: "Rheology modifier", def: "A thickener that controls viscosity, sag resistance and flow/levelling of paints and adhesives." },
  { term: "Rub fastness (crocking)", def: "Resistance of a printed or dyed fabric to colour transfer when rubbed, tested dry and wet." },
  { term: "Rubberised coir", def: "Coir fibre bonded with latex into resilient sheets used for mattresses, cushions and upholstery.", related: "/learning-center/latex-vs-synthetic-emulsion-for-rubberised-coir" },
  { term: "SBR", def: "Styrene Butadiene Rubber latex — a common cement modifier in waterproofing and repair mortars." },
  { term: "Scrub resistance", def: "A paint film's ability to withstand repeated wet scrubbing, largely determined by binder type and PVC." },
  { term: "Shelf life", def: "The period an unopened product remains within specification when stored as recommended. Enfixx adhesives: 12 months in cool, shaded storage." },
  { term: "Solids content", def: "The percentage of non-volatile material (mainly polymer) in an emulsion or adhesive." },
  { term: "Styrene acrylic", def: "A copolymer of styrene and acrylic monomers — a cost-effective, water- and alkali-resistant binder for interior paints, primers and putty.", related: "/learning-center/styrene-acrylic-vs-pure-acrylic-emulsion" },
  { term: "Synthetic resin adhesive", def: "The trade term in India for white PVAc-based wood glue, sold under brands such as Enfixx.", related: "/learning-center/pva-wood-glue-vs-synthetic-resin-adhesive" },
  { term: "TDS", def: "Technical Data Sheet — a document listing a product's typical properties, application guidance and storage conditions.", related: "/downloads" },
  { term: "MSDS / SDS", def: "(Material) Safety Data Sheet — a document describing hazards, handling, storage and emergency measures for a chemical product.", related: "/downloads" },
  { term: "VOC", def: "Volatile Organic Compounds — solvents that evaporate into the air. Water-based emulsions and adhesives are low-VOC alternatives to solvent systems." },
  { term: "Wash fastness", def: "Resistance of a textile print or dye to colour loss during laundering." },
  { term: "Wet tack", def: "The initial grab of a wet adhesive that holds parts in place before the bond cures." },
];

export const termSlug = (t: string) => "term-" + t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, "");
